blank_issues_enabled: false
contact_links:
  - name: Question / Help
    url: https://github.com/misha-mad/metaxy/discussions/categories/q-a
    about: Ask questions and get help in Discussions
  - name: Ideas / Brainstorming
    url: https://github.com/misha-mad/metaxy/discussions/categories/ideas
    about: Share open-ended ideas in Discussions
